"""Redis-backed session management for Vaidya voice sessions.

Each phone call gets a :class:`ConversationContext` stored in Redis with
a configurable TTL (default 30 min).  Dropped-call recovery is implicit:
if the same caller rings back within the TTL, the session resumes from
where it left off.
"""

from __future__ import annotations

import hashlib
import logging
import time
from datetime import UTC, datetime

import redis.asyncio as aioredis

from vaidya.models.conversation import ConversationContext, ConversationPhase

logger = logging.getLogger(__name__)

_KEY_PREFIX = "vaidya:session:"


class SessionManager:
    """Redis-backed conversation session state.

    Lifecycle::

        mgr = SessionManager("redis://localhost:6379/0")
        ctx = await mgr.create("call-123", phone_hash="abc", language="hi-IN")
        # ... agent turns ...
        await mgr.update(ctx)
        # ... later ...
        ctx = await mgr.get("call-123")  # resumes
        await mgr.delete("call-123")     # cleanup
        await mgr.close()
    """

    def __init__(self, redis_url: str, ttl_seconds: int = 1800) -> None:
        self._redis = aioredis.from_url(redis_url, decode_responses=True)
        self._ttl = ttl_seconds

    # ------------------------------------------------------------------
    # Create
    # ------------------------------------------------------------------

    async def create(
        self,
        call_id: str,
        phone_hash: str = "",
        language: str = "hi-IN",
    ) -> ConversationContext:
        """Create a new conversation session and persist it.

        Parameters
        ----------
        call_id:
            Unique call identifier (generated by the caller or
            :meth:`generate_call_id`).
        phone_hash:
            SHA-256 hash of the caller's phone number (PII-safe).
        language:
            BCP-47 language tag for the session (e.g. ``"hi-IN"``).

        Returns
        -------
        ConversationContext
            The newly created, empty context.
        """
        context = ConversationContext(
            call_id=call_id,
            phone_number_hash=phone_hash,
            language=language,
            phase=ConversationPhase.WELCOME,
        )
        await self.update(context)
        logger.info(
            "Session created",
            extra={"call_id": call_id, "language": language},
        )
        return context

    # ------------------------------------------------------------------
    # Read
    # ------------------------------------------------------------------

    async def get(self, call_id: str) -> ConversationContext | None:
        """Load a session from Redis.

        Returns ``None`` if the session does not exist or has expired.
        """
        key = f"{_KEY_PREFIX}{call_id}"
        try:
            data = await self._redis.get(key)
        except Exception as exc:
            logger.error(
                "Redis GET failed",
                extra={"call_id": call_id, "error": str(exc)},
            )
            return None

        if data is None:
            return None

        try:
            return ConversationContext.model_validate_json(data)
        except Exception as exc:
            logger.error(
                "Session deserialisation failed",
                extra={"call_id": call_id, "error": str(exc)},
            )
            return None

    # ------------------------------------------------------------------
    # Update
    # ------------------------------------------------------------------

    async def update(self, context: ConversationContext) -> None:
        """Serialise *context* to Redis and refresh the TTL.

        This should be called after every agent turn so the TTL stays fresh.
        """
        key = f"{_KEY_PREFIX}{context.call_id}"
        context.updated_at = datetime.now(UTC)
        try:
            data = context.model_dump_json()
            await self._redis.setex(key, self._ttl, data)
        except Exception as exc:
            logger.error(
                "Redis SETEX failed",
                extra={"call_id": context.call_id, "error": str(exc)},
            )

    # ------------------------------------------------------------------
    # Delete
    # ------------------------------------------------------------------

    async def delete(self, call_id: str) -> None:
        """Remove a session from Redis (explicit cleanup after call ends)."""
        key = f"{_KEY_PREFIX}{call_id}"
        try:
            await self._redis.delete(key)
            logger.info("Session deleted", extra={"call_id": call_id})
        except Exception as exc:
            logger.error(
                "Redis DELETE failed",
                extra={"call_id": call_id, "error": str(exc)},
            )

    # ------------------------------------------------------------------
    # Utilities
    # ------------------------------------------------------------------

    async def exists(self, call_id: str) -> bool:
        """Check whether a session exists (without loading it)."""
        key = f"{_KEY_PREFIX}{call_id}"
        try:
            return bool(await self._redis.exists(key))
        except Exception as exc:
            logger.error(
                "Redis EXISTS failed",
                extra={"call_id": call_id, "error": str(exc)},
            )
            return False

    async def close(self) -> None:
        """Close the Redis connection pool."""
        try:
            await self._redis.aclose()
            logger.info("SessionManager Redis connection closed")
        except Exception as exc:
            logger.error("Redis close failed", extra={"error": str(exc)})

    @staticmethod
    def generate_call_id(phone_hash: str) -> str:
        """Generate a unique, time-stamped call ID.

        The ID is a 16-char hex string derived from the phone hash and
        the current time, ensuring uniqueness across calls from the same
        number.
        """
        raw = f"{phone_hash}-{time.time()}"
        return hashlib.sha256(raw.encode()).hexdigest()[:16]
