"""Bilingual keyword lists for heuristic field identification in transcripts.

Used by the ConvergenceChecker to determine whether the conversation
transcript contains evidence about a disputed eligibility field.
"""

FIELD_KEYWORDS: dict[str, list[str]] = {
    "income": [
        "income",
        "kamai",
        "amdani",
        "salary",
        "tankha",
        "paisa",
        "rupee",
        "lakh",
        "hazaar",
        "maheena",
        "month",
        "saal",
        "year",
        "bpl",
        "gareebi",
        "below poverty",
    ],
    "age": [
        "age",
        "umar",
        "saal",
        "years old",
        "baras",
        "budha",
        "baccha",
        "child",
        "senior",
        "bujurg",
    ],
    "state": [
        "state",
        "rajya",
        "pradesh",
        "district",
        "zila",
        "gaon",
        "village",
        "city",
        "shehar",
    ],
    "family_size": [
        "family",
        "parivar",
        "ghar",
        "member",
        "bacche",
        "children",
        "log",
        "sadasya",
    ],
    "occupation": [
        "kaam",
        "naukri",
        "job",
        "occupation",
        "majdoor",
        "kisan",
        "farmer",
        "daily wage",
        "dihadi",
        "salaried",
        "self employed",
        "rozgaar",
        "vyapar",
        "business",
    ],
    "bpl_card": [
        "bpl",
        "ration card",
        "rashan",
        "below poverty",
        "gareebi rekha",
        "antyodaya",
        "priority household",
    ],
    "coverage": [
        "insurance",
        "bima",
        "coverage",
        "cashless",
        "hospital",
        "ayushman",
        "scheme",
        "yojana",
        "card",
    ],
    "secc": [
        "secc",
        "deprivation",
        "kachha",
        "kutcha",
        "sc",
        "st",
        "scheduled caste",
        "scheduled tribe",
        "obc",
        "category",
    ],
    "documents": [
        "aadhaar",
        "aadhar",
        "pan",
        "document",
        "dastavez",
        "kaagaz",
        "certificate",
        "pramaan patra",
    ],
}
